az-configuration:
- name: ((az1))
- name: ((az2))
- name: ((az3))
network-assignment:
  network:
    name: infrastructure
  singleton_availability_zone:
    name: eu-west-2a
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: ((subdomain-name))-pcf-network/((subdomain-name))-infrastructure-subnet/us-central1
      cidr: 10.0.0.0/26
      dns: 169.254.169.254
      gateway: 10.0.0.1
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
  - name: pks
    subnets:
    - iaas_identifier: ((subdomain-name))-pcf-network/((subdomain-name))-pks-subnet/us-central1
      cidr: 10.0.10.0/24
      dns: 169.254.169.254
      gateway: 10.0.10.1
      reserved_ip_ranges: 10.0.10.1-10.0.10.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
  - name: pks-services
    subnets:
    - iaas_identifier: ((subdomain-name))-pcf-network/((subdomain-name))-pks-services-subnet/us-central1
      cidr: 10.0.11.0/24
      dns: 169.254.169.254
      gateway: 10.0.11.1
      reserved_ip_ranges: 10.0.11.1-10.0.11.9
      availability_zone_names:
      - us-central1-a
      - us-central1-b
      - us-central1-c
properties-configuration:
  director_configuration:
    ntp_servers_string: 0.amazon.pool.ntp.org,1.amazon.pool.ntp.org,2.amazon.pool.ntp.org,3.amazon.pool.ntp.org
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
  iaas_configuration:
    project: ((gcp-project-id))
    default_deployment_tag: ((subdomain-name))
    auth_json: ((gcp-credentials))
resource-configuration:
  compilation:
    instances: 8
